server.port: 8084

# 외부 DB 설정시 아래의 주석을 활성화 시킨 후 관련 DB 설정 정보를 입력한다.
spring:
  datasource:
    url: jdbc:mysql://algo.cphno6qganog.ap-northeast-2.rds.amazonaws.com:3306/scraping
    driverClassName: com.mysql.jdbc.Driver
    username: algoalgo
    password: algoalgo

logging.level:
  org.springframework:
    security: debug
    boot: debug